### PR TITLE
Fetch text via hash accessor.

### PR DESCRIPTION
**Pull request by robholland**
Data is a hash, not a mash.

### CODE REVIEW

**Comment by robholland** [comment]
Fixes:

```
12:28:29 web.1  | E, [2021-01-05T12:28:29.455835 #57673] ERROR -- : NoMethodError: undefined method `text' for #<ActiveSupport::HashWithIndifferentAccess:0x00007fcd04b77e00>
12:28:29 web.1  |   /Users/.../vendor/bundle/gems/slack-ruby-bot-server-events-app-mentions-0.1.0/lib/slack-ruby-bot-server-events-app-mentions/events.rb:14:in `block (2 levels) in <top (required)>'
```

**Comment by dblock** [comment]
Thanks! Why am I not seeing this in https://github.com/slack-ruby/slack-ruby-bot-server-events-app-mentions-sample? 

This needs a spec, please.

**Comment by robholland** [comment]
Confirmed red/green by pushing fixed spec alongside old code. I'm not sure why you don't see this issue in your sample app.

**Comment by robholland** [comment]
As an aside it would be great if you could add docker-compose files so it's easy to run your specs without fighting with bundler or having to setup/configure databases to run locally.

**Comment by dblock** [comment]
I can actually reproduce. Not sure what happened when I was working on that sample. Merged via https://github.com/slack-ruby/slack-ruby-bot-server-events-app-mentions/commit/ae03b3ff2785e726506efbe5e967aba7c7c1b402, thanks. 

Re: docker compose, feel free to PR, although I am pretty sure we can resolve the local test issue in some other way - what's your error when you run `rake`?

**Comment by dblock** [comment]
I released 0.1.1.

**Pull request closed without merging**
